// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservasCanchas.DataAccess.Persistance;

#nullable disable

namespace ReservasCanchas.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251114003216_AddSomeEnums")]
    partial class AddSomeEnums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComplejoService", b =>
                {
                    b.Property<int>("ComplexesId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicesId")
                        .HasColumnType("integer");

                    b.HasKey("ComplexesId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ComplexService", (string)null);
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Complejo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("AditionalIlumination")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PercentageSign")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartIlumination")
                        .HasColumnType("time without time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Complejo");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("ComplexId")
                        .HasColumnType("integer");

                    b.Property<bool>("Covered")
                        .HasColumnType("boolean");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<int>("FloorType")
                        .HasColumnType("integer");

                    b.Property<decimal>("HourPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("Ilumination")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.RecurringFieldBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time without time zone");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("InitHour")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("RecurringFieldBlock");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("InitTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("PayType")
                        .HasColumnType("integer");

                    b.Property<int>("PrecioPagado")
                        .HasColumnType("integer");

                    b.Property<int>("ReservationState")
                        .HasColumnType("integer");

                    b.Property<int>("ReservationType")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.ToTable("Review");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.TimeSlotComplex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplexId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("InitTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("TimeSlotComplex");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.TimeSlotField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("InitTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("TimeSlotField");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ComplejoService", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Complejo", null)
                        .WithMany()
                        .HasForeignKey("ComplexesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasCanchas.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Complejo", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Usuario", "User")
                        .WithMany("Complejos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Field", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Complejo", "Complex")
                        .WithMany("Fields")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.RecurringFieldBlock", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Field", "Field")
                        .WithMany("recurringCourtBlocks")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Field", "Field")
                        .WithMany("Reservations")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasCanchas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Review", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reviews")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasCanchas.Domain.Entities.Reservation", "Reservation")
                        .WithOne("Review")
                        .HasForeignKey("ReservasCanchas.Domain.Entities.Review", "ReservationId");

                    b.Navigation("Reservation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.TimeSlotComplex", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Complejo", "Complex")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.TimeSlotField", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Field", "Field")
                        .WithMany("TimeSlotsField")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Complejo", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Field", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("TimeSlotsField");

                    b.Navigation("recurringCourtBlocks");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Complejos");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
