// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservasCanchas.DataAccess.Persistance;

#nullable disable

namespace ReservasCanchas.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108002545_AddEntitiesAndRelationships")]
    partial class AddEntitiesAndRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComplejoService", b =>
                {
                    b.Property<int>("ComplexesId")
                        .HasColumnType("integer");

                    b.Property<int>("ServicesId")
                        .HasColumnType("integer");

                    b.HasKey("ComplexesId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ComplexService", (string)null);
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Complejo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("AditionalIlumination")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PercentageSign")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartIlumination")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Complejo");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<int>("ComplexId")
                        .HasColumnType("integer");

                    b.Property<bool>("Covered")
                        .HasColumnType("boolean");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<int>("FloorType")
                        .HasColumnType("integer");

                    b.Property<int>("HourPrice")
                        .HasColumnType("integer");

                    b.Property<bool>("Ilumination")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.RecurringCourtBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndHour")
                        .HasColumnType("time without time zone");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("InitHour")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("RecurringCourtBlock");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("InitTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("PrecioPagado")
                        .HasColumnType("integer");

                    b.Property<int>("ReservationType")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.TimeSlotComplex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComplexId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("InitTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComplexId")
                        .IsUnique();

                    b.ToTable("TimeSlotComplex");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.TimeSlotField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("FieldId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("InitTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldId")
                        .IsUnique();

                    b.ToTable("TimeSlotField");
                });

            modelBuilder.Entity("ComplejoService", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Complejo", null)
                        .WithMany()
                        .HasForeignKey("ComplexesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasCanchas.Domain.Entities.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Field", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Complejo", "Complex")
                        .WithMany("Fields")
                        .HasForeignKey("ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.RecurringCourtBlock", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Field", "Field")
                        .WithMany("recurringCourtBlocks")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Field", "Field")
                        .WithMany("Reservations")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.TimeSlotComplex", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Complejo", "Complex")
                        .WithOne("TimeSlotComplex")
                        .HasForeignKey("ReservasCanchas.Domain.Entities.TimeSlotComplex", "ComplexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complex");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.TimeSlotField", b =>
                {
                    b.HasOne("ReservasCanchas.Domain.Entities.Field", "Field")
                        .WithOne("TimeSlotField")
                        .HasForeignKey("ReservasCanchas.Domain.Entities.TimeSlotField", "FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Complejo", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("TimeSlotComplex")
                        .IsRequired();
                });

            modelBuilder.Entity("ReservasCanchas.Domain.Entities.Field", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("TimeSlotField")
                        .IsRequired();

                    b.Navigation("recurringCourtBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
